In [ ]:
#Практическое задание №6

In [8]:
#6. Найдите одно из псевдорешений вырожденной системы
#|1 2 3|       | 2|
#|4 5 6| * X = | 5|
#|7 8 9|       |11|

import numpy as np
import matplotlib.pyplot as plt
import scipy
import scipy.linalg

print("QR разложение.")
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([2, 5, 11])
Q, R = np.linalg.qr(A)
print("A = \n", A)
print("Q = \n", Q)
print("R = \n", R)
print("Проверим полученные значения матрицы Q и R (получим матрицу A): \n", np.dot(Q, R))
print("Проверим полученную матрицу Q \n" , np.dot(np.transpose(Q), Q))
R1 = R[:2, :2]
print("Получим подматицу R1 = \n", R1)
B1 = np.dot(np.transpose(Q), B)[:2]
X1 = np.linalg.solve(R1, B1)
print("X1: \n", X1)
X = np.append(X1, 0)
print("При X2 = 0 X примит вид: \n", X)
print("Норма первого найденного псевдорешения: ", np.linalg.norm(X))
print("Норма псевдорешения с невязкой: ", np.linalg.norm(np.dot(A, X) - B))

print("Нормальное псевдорешение при помощи linalg.lstsq: \n", np.linalg.lstsq(A,B, rcond = None))


QR разложение.
A = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Q = 
 [[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
R = 
 [[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -8.88178420e-16]]
Проверим полученные значения матрицы Q и R (получим матрицу A): 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Проверим полученную матрицу Q 
 [[ 1.00000000e+00 -2.48218629e-16 -2.62094065e-17]
 [-2.48218629e-16  1.00000000e+00  2.82872043e-17]
 [-2.62094065e-17  2.82872043e-17  1.00000000e+00]]
Получим подматицу R1 = 
 [[-8.1240384  -9.6011363 ]
 [ 0.          0.90453403]]
X1: 
 [1.50000000e+00 3.92767275e-15]
При X2 = 0 X примит вид: 
 [1.50000000e+00 3.92767275e-15 0.00000000e+00]
Норма первого найденного псевдорешения:  1.499999999999996
Норма псевдорешения с невязкой:  1.224744871391589
Нормальное псевдорешение при помощи linalg.lstsq: 
 (array([ 1.25,  0.5 , -0